# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1482110506);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1482110626);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1482126569);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1482113866);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1482110386);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1482110746);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1478497893424");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1478499663424");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1475323679252");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1475327279252");
user_pref("browser.search.countryCode", "JP");
user_pref("browser.search.region", "JP");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160921132349");
user_pref("browser.slowStartup.averageTime", 5903);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20160921132349");
user_pref("browser.startup.homepage_override.mstone", "45.4.0");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1475389611794");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1475312878988");
user_pref("datareporting.policy.firstRunTime", "1475303211793");
user_pref("datareporting.sessions.current.activeTicks", 25);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 5922);
user_pref("datareporting.sessions.current.main", 1742);
user_pref("datareporting.sessions.current.sessionRestored", 6250);
user_pref("datareporting.sessions.current.startTime", "1482126445603");
user_pref("datareporting.sessions.current.totalTime", 2750);
user_pref("datareporting.sessions.currentIndex", 13);
user_pref("datareporting.sessions.previous.10", "{\"s\":1482110140533,\"a\":42,\"t\":4183,\"c\":true,\"m\":1291,\"fp\":10223,\"sr\":10553}");
user_pref("datareporting.sessions.previous.11", "{\"s\":1482114326947,\"a\":19,\"t\":95,\"c\":true,\"m\":761,\"fp\":5466,\"sr\":5550}");
user_pref("datareporting.sessions.previous.12", "{\"s\":1482114429280,\"a\":4,\"t\":26,\"c\":false,\"m\":492,\"fp\":3434,\"sr\":3500}");
user_pref("datareporting.sessions.prunedIndex", 9);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 7);
user_pref("extensions.blocklist.pingCountVersion", 7);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"/usr/lib64/firefox/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"langpack-ja@firefox.mozilla.org\":{\"version\":\"45.4.0\",\"type\":\"locale\",\"descriptor\":\"/home/neec/.mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/langpack-ja@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.4.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1478484462);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.4.0");
user_pref("extensions.lastPlatformVersion", "45.4.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/usr/lib64/firefox/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1474465072000}},\"app-system-user\":{\"langpack-ja@firefox.mozilla.org\":{\"d\":\"/home/neec/.mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/langpack-ja@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"45.4.0\",\"st\":1474465103000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.4.0\",\"st\":1474465072000}}}");
user_pref("gecko.buildID", "20160921132349");
user_pref("gecko.mstone", "45.4.0");
user_pref("idle.lastDailyNotification", 1482110742);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1475312931);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20160921132349");
user_pref("media.gmp-manager.lastCheck", 1475312930);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1482110743);
user_pref("places.history.expiration.transient_current_max_pages", 26032);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1482110743);
user_pref("toolkit.startup.last_success", 1482126447);
user_pref("toolkit.telemetry.cachedClientID", "8d26628e-4762-4967-8b51-86dd4c202e24");
user_pref("toolkit.telemetry.previousBuildID", "20160921132349");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
